---
author: ""
---

# Workshop Schedule {.unnumbered}

|Instructors | Emails |
|:--|:--|
| Amy Winter | awinter *at* uga *dot* edu |
| Matt Ferrari (Penn State University) | mjf283 *at* psu *dot* edu |

: {.striped .hover tbl-colwidths="[60,40]"}

**General workshop times**:

July 14, Monday: 9:00 a.m. - 5 p.m. EDT

July 15, Tuesday: 9:00 a.m. - 5 p.m. EDT

July 16, Wednesday: 9:00 a.m. - 12 p.m. EDT

::: {.callout-important}
All times are in local time EDT (Eastern Daylight Time).
:::

## Before class

Please see pre-requisites on the course website

## Day 01 – Monday 

| Time | Section |
|:--|:--|
| 9:00 - 9:30am | Welcome and Introductions |
| 9:30 - 10am | Lecture 1: Introduction to ID Models by Amy Winter |
| 10 - 10:30pm | coffee break |
| 10:30am - 11:30 am | Lecture 2: Basics of SIR Models by Matt Ferrari |
| 11:30 - 12pm | `R` Session 1: Intro to modeling by Matt Ferrari |
| 12 - 1:30pm | lunch on your own |
| 1:30pm - 2:30pm | `R` Session 1: Intro to modeling (continued) by Matt Ferrari |
| 2:30pm - 3pm | Lecture 3: Vaccination & Interventions by Matt Ferrari |
| 3pm - 3:30pm | Coffee break |
| 3:30pm - 4:00pm | Lecture 3: Vaccination & Interventions by Matt Ferrari |
| 4:00pm - 5pm | Interactive Session |
| 5pm - 7pm | SISMID-wide networking mixer |
: {.striped .hover tbl-colwidths="[25,75]"}


## Day 02 – Tuesday

| Time | Section |
|:--|:--|
| 9:00am - 10:00am | Lecture 4: Heterogeneity and Age Structure by Amy Winter |
| 10 - 10:30am | Coffee Break |
| 10:30 - 12am | `R` Session 2: Heterogeneity and Age structure by Matt Ferrari |
| 12 - 1:30pm | lunch on your own / SISMID-wide optional professional development module |
| 1:30 - 2:30pm | Lecture 5: Parameter Estimation (estimating $R_0$) by Matt Ferrari |
| 2:30 - 3:00pm | `R` Session 3: Parameter estimation by Matt Ferrari |
| 3pm - 3:30pm | Coffee break |
| 3:30pm - 4:00pm | `R` Session 3: Parameter estimation by Matt Ferrari |
| 4:00pm - 5pm | Group Discussion |
| 5pm - 7pm | SISMID-wide social activity |
: {.striped .hover tbl-colwidths="[25,75]"}

## Day 03 – Wednesday

| Time | Section |
|:--|:--|
| 9:00am - 9:30am | Lecture 7: Confronting models with data by Amy Winter |
| 9:30am - 10am | Lecture 8: Stochasticity and Uncertainty lecture by Amy Winter and Matt Ferrari (first half) |
| 10am - 10:30am | Coffee break |
| 10:30am - 11am | Lecture 8: Stochasticity and Uncertainty lecture by Amy Winter and Matt Ferrari (first half) |
| 11am - 12am | Group Assignment debrief for `R` Session 3 and any other discussion points |

: {.striped .hover tbl-colwidths="[25,75]"}

**Class Ends Noon on Wednesday**

## Group assignments
- Each individual should create a slide deck to address each of the following questions for each of the day’s `R` exercises.
- Each group should develop consensus slides to present when we come together as a class.
- Groups will be asked to share their intuition gained.

**Questions**:

1. What were the top two take-away messages you gained from this `R` exercise?
2. What was the most unexpected/non-intuitive thing you learned from this `R` exercise?
